[package]
name = "rmarkr"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = { version = "0.9.1", default-features = false, features = ["simd"] }
druid = { git = "https://github.com/linebender/druid.git" }
open = "1.6"
