name: Rust CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@master
    - name: Build & Test
      run: |
        sudo apt-get update
        sudo apt-get install -y libpango1.0-dev libatk1.0-0 libatk1.0-dev libgtk-3-dev
        rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
        cargo test 

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Rustfmt Check
      run: |
        rustup update stable && rustup default stable && rustup component add rustfmt
        cargo fmt -- --check

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get update
          sudo apt-get install -y libpango1.0-dev libatk1.0-0 libatk1.0-dev libgtk-3-dev
          rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
